Add backport_pr.yaml action

diff --git a/.github/workflows/backport_pr.yaml b/.github/workflows/backport_pr.yaml
--- a/.github/workflows/backport_pr.yaml
+++ b/.github/workflows/backport_pr.yaml
@@ -26,9 +26,16 @@ jobs:
           git_config_global: true
           git_user_signingkey: true
           git_commit_gpgsign: true
-      - name: Test phrase
+      - name: Verify Secret Presence
+        env:
+          MY_SECRET: ${{ secrets.CHACI_GPG_PASSPHRASE }}
         run: |
-          echo "${{ secrets.CHACI_GPG_PASSPHRASE }}" | sed 's/./& /g'
+          if [ -z "$MY_SECRET" ]; then
+            echo "❌ Secret is EMPTY or MISSING"
+            exit 1
+          else
+            echo "✅ Secret is SET. Length: ${#MY_SECRET} characters"
+          fi
       - name: Create backport pull requests
         uses: korthout/backport-action@v3
         with:
